### ISSUE TITLE
[Fix] 디테일 수정

### ISSUE THREAD

**Issue by seung-heee** [URECA-FINAL-TEAM2/frontend#113]
## 🚀 Description
통합테스트 이후 디테일 수정

## ✅ TODO
- [x]  마이페이지 : 예약내역 아이콘 변경하기
- [x]  프로필 수정 : 수정불가능한 요소들 회색 → 좀더 진한 회색
- [x]  고객쪽 매장 정보 ← 난 모르겟는데 아까 승희가 뭔가 디자인이 애매하다고 함
- [x]  매장상세 ShopMenubar sticky 속성: 미용사>내매장에서는 적용됨, 고객>미용사찾기에서는 적용안됨.
- [x]  “반려견 정보를 확인해주세요.” → “성별을 선택해주세요.” 이런 식으로 전체적으로 유효성 검사하고 토스트 메시지 구체화
