### ISSUE TITLE
[알림 FIX] 알림 API 추가, 퍼블리싱 수정

### ISSUE THREAD

**Issue by seung-heee** [URECA-FINAL-TEAM2/frontend#115]
## 🚀 Description
알림 클릭시 읽음처리 API 추가,
퍼블리싱 수정

## ✅ TODO
- [x] 알림 클릭시 읽음 처리 API 추가
- [x] 알림 목록 스크롤 안됨
- [x] 경고문구추가 - 2주 뒤 알림 소멸
- [x] 빨간 점 크기 다름
