### ISSUE TITLE
[Fix] 디테일 개선

### ISSUE THREAD

**Issue by hongsi0** [URECA-FINAL-TEAM2/frontend#120]
---
## 🚀 Description
최종적으로 추가할 사소한 기능 및 디테일 수정사항

## ✅ TODO
- [x] 이미지 모달 추가
- [x] 지도 마커 디자인 변경
- [x] 지역선택 모달에서 default value 지정
- [x] 토스트 알림 추가
- [x] 결제 완료 페이지에 예약내역 바로가기 버튼 추가
- [x] 고객 견적요청 페이지 수정 (채팅하기 -> 매장 상세 보기)
- [x] 견적요청/견적서 페이지 (CustomerQuote, GroomerQuote) 탭 구분 + 해당 페이지로의 navigate 수정
- [x] 미용사의 보낸 견적서 탭의 status 텍스트 정제
- [x] 미용사의 견적서 페이지 전체 -> 등록된 매장이 없는 경우 EmptyPage
- [x] 버튼 컴포넌트 통일 (고객 마이페이지 리뷰 관리, 예약 목록, 견적서/견적요청 페이지)
- [x] 고객이 올린 공고에서 견적서들 간 정렬
- [x] 고객이 올린 공고- 견적 그만 받기 구현 or 버튼 삭제
