### ISSUE TITLE
[프로필 관리] 미용사 매장정보 CRUD

### ISSUE THREAD

**Issue by seung-heee** [URECA-FINAL-TEAM2/frontend#17]
## ✅ TODO
- [x] 미용사 매장정보 생성
- [x] 미용사 매장정보 조회
- [x] 미용사 매장정보 수정
- [x] 미용사 매장정보 삭제
