### ISSUE TITLE
[메인] 고객, 미용사 메인 상세

### ISSUE THREAD

**Issue by seung-heee** [URECA-FINAL-TEAM2/frontend#21]
## 🚀 고객, 미용사 메인화면 상세 구현

고객과 미용사가 볼 수 있는 화면을 다르게 구성하여 각 메인페이지를 구현한다.
백엔드와의 통신 구현

## ✅ TODO
- [x] 고객 - BEST 미용 후기 조회
- [x] 고객 - 우리동네 디자이너 조회
- [x] 미용사 - 오늘의 예약 건수 조회
- [x] 미용사 - 1:1 견적 요청 건수 조회(전체, 오늘 요청, 견적 미발송)
- [x] 미용사 - 우리동네 견적 공고 조회
