### ISSUE TITLE
[알림] 실시간 알림 구현

### ISSUE THREAD

**Issue by seung-heee** [URECA-FINAL-TEAM2/frontend#22]
## 🚀 알림창 구현
견적을 받을 때, 보낼 때, 채팅 시 등 사용자가 받는 알람을 조회할 수 있는 페이지를 구현한다.

## ✅ TODO
- [x] SSE 연결
- [x] 실시간 알림 조회
- [x] 알림 삭제
- [x] 전체 알림 삭제
- [x] 전역상태관리 -> 메인에서 안 읽은 알림 수 조회
