### ISSUE TITLE
[프로필관리] 미용사의 내 매장 미리보기 페이지 구현

### ISSUE THREAD

**Issue by hongsi0** [URECA-FINAL-TEAM2/frontend#77]
## 🚀 Description
본인 매장을 미리보기 식으로 조회하는 페이지 구현
미용사 찾기 하위의 매장 상세 페이지와 동일한 형식 - 찜 여부, 리뷰의 좋아요 여부 제외

## ✅ TODO
- [x] 매장 소개 인트로 (최상단)
- [x] 메뉴 바
- [x] 매장 정보 (운영시간, 주소, 위치)
- [x] 포트폴리오
- [x] 미용사 정보
- [x] 리뷰
- [x] 매장 수정 페이지로 이동하는 플로팅 버튼
