### ISSUE TITLE
[프로필 관리] 고객(사용자) 프로필 CRUD

### ISSUE THREAD

**Issue by seung-heee** [URECA-FINAL-TEAM2/frontend#9]
## ✅ TODO
- [ ] 고객 프로필 등록
- [ ] 고객 프로필 조회
- [ ] 고객 프로필 수정
- [ ] 고객 프로필 삭제
